import { useEffect, useMemo, useRef, useState } from "react"
import { Link } from "react-router-dom"
import { AnimatePresence, motion, type Variants } from "framer-motion"
import {
  Activity,
  AlertTriangle,
  ArrowRight,
  BookOpen,
  ChevronDown,
  Download,
  LifeBuoy,
  ShieldCheck,
} from "lucide-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import { cn } from "@/lib/utils"
import { useAuth } from "@/hooks/useAuth"

type FaqItem = { q: string; a: string }
type FaqCategory = { id: string; label: string; icon: typeof ShieldCheck; items: FaqItem[] }

type GuideSection = { title: string; body: string }

const SUPPORT_EMAIL = "support@aura-dx.xyz"
const SKELETON_MS = 450

const container: Variants = {
  hidden: {},
  show: { transition: { staggerChildren: 0.07, delayChildren: 0.05 } },
}
const item: Variants = {
  hidden: { opacity: 0, y: 14 },
  show: { opacity: 1, y: 0, transition: { duration: 0.42, ease: [0.22, 1, 0.36, 1] } },
}

export function HelpSupport() {
  const { user } = useAuth()
  const role = user?.role
  const isAdmin = role === "admin" || role === "super_admin"

  const [loading, setLoading] = useState(true)
  const [openItems, setOpenItems] = useState<Set<string>>(new Set())
  const guideRef = useRef<HTMLElement>(null)

  /* Simulated mount load so skeletons are visible while the page settles. */
  useEffect(() => {
    const t = setTimeout(() => setLoading(false), SKELETON_MS)
    return () => clearTimeout(t)
  }, [])

  /* ---- Role-aware FAQ content ---- */
  const categories = useMemo<FaqCategory[]>(() => {
    const base: FaqCategory[] = [
      {
        id: "account",
        label: "Account & Access",
        icon: ShieldCheck,
        items: [
          {
            q: "How do I reset my password?",
            a: "On the sign-in screen, choose “Forgot password”. We send a secure reset link to your registered email. The link expires after 60 minutes for security.",
          },
          {
            q: "What roles exist in AURA-Dx?",
            a: "Clinicians can capture screenings and manage patient records. Admins and Super Admins can manage users, roles, and the system audit log. All permissions are enforced server-side, not just in the UI.",
          },
          {
            q: "How do I check my approval status?",
            a: "New accounts stay “pending” until a Super Admin approves them. You’ll see a status banner on sign-in. If approval is delayed, contact support@aura-dx.xyz.",
          },
        ],
      },
      {
        id: "screening",
        label: "Screening Workflows",
        icon: Activity,
        items: [
          {
            q: "How do I capture a cough sample?",
            a: "Open New Screening, grant microphone access, and record one or two natural coughs — or upload an audio file. An explicit consent step always runs before any audio is captured.",
          },
          {
            q: "How do I review screening results?",
            a: "The screening detail view shows the classification (TB, COPD, Pneumonia, Healthy) with a confidence score. Results flagged as low-confidence are routed to a clinician for manual review.",
          },
          {
            q: "How do I export a patient PDF report?",
            a: "Open the patient or screening detail and choose Export PDF. A clinical report (generated by ReportLab) downloads with the results, metadata, and reviewer sign-off.",
          },
        ],
      },
      {
        id: "technical",
        label: "Technical Troubleshooting",
        icon: AlertTriangle,
        items: [
          {
            q: "My microphone isn’t detected. What should I do?",
            a: "Check the browser site permission for the microphone, use a recent Chrome or Edge build, and ensure the page is served over HTTPS. Built-in OS privacy controls can also block access.",
          },
          {
            q: "Which browsers are supported?",
            a: "The latest Chrome, Edge, Firefox, and Safari are supported. Internet Explorer is not. Keep your browser updated for the best audio-capture experience.",
          },
          {
            q: "An audio upload failed — why?",
            a: "Confirm the file is WAV, M4A, or MP3 and under 10 MB, and that your connection is stable. Very long or corrupted clips are rejected before processing.",
          },
          {
            q: "The app won’t load.",
            a: "Clear the browser cache and reload. A degraded backend or database will block sign-in and screening, so retry after a short wait.",
          },
        ],
      },
    ]

    if (isAdmin) {
      base[0].items.push(
        {
          q: "How do I approve a new user?",
          a: "Open Admin → Users, review pending accounts, and Approve or Reject each one. Approved clinicians can immediately begin screening.",
        },
        {
          q: "How do I change a user’s role?",
          a: "In Admin → Users you can promote a clinician to admin (and vice versa). The Super Admin role is protected. Role changes take effect the next time the user signs in.",
        },
        {
          q: "Where can I audit system activity?",
          a: "The Admin audit log records sign-ins, screening events, exports, and role changes with timestamps, so you can review who did what and when.",
        }
      )
    } else {
      base[1].items.push(
        {
          q: "How do I manage patient records?",
          a: "Use the Patient Records tab to search patients, open a detail view, and review their full screening history. Records are shared across the clinic — there is no per-clinician scoping.",
        },
        {
          q: "Any tips for consistent cough captures?",
          a: "Record in a quiet room, hold the device 10–15 cm from the mouth, and capture one or two clear coughs. Consistent technique improves classification confidence.",
        }
      )
    }

    return base
  }, [isAdmin])

  function toggleItem(id: string) {
    setOpenItems((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  /* ---- User guide (view + download) ---- */
  const guideSections = useMemo<GuideSection[]>(() => {
    const shared: GuideSection[] = [
      {
        title: "1. Signing in safely",
        body: "Always sign in from the official portal over HTTPS. Never share your password. If you suspect unauthorized access, reset your password and notify support@aura-dx.xyz immediately.",
      },
      {
        title: "2. Capturing a screening",
        body: "Open New Screening, read and accept the consent prompt, then record one or two coughs or upload a clip. Wait for the classification and confidence score before acting on a result.",
      },
      {
        title: "3. Reviewing and exporting",
        body: "Open any screening from Patient Records to see the full result. Use Export PDF to generate a clinical report for the patient file or referral.",
      },
    ]
    if (isAdmin) {
      return [
        ...shared,
        {
          title: "4. Approving and managing users",
          body: "Admins review pending accounts in Admin → Users, approve or reject them, and adjust roles as needed. The audit log records every administrative action.",
        },
        {
          title: "5. System auditing",
          body: "Periodically review the audit log for unusual sign-ins or exports. Treat any unexpected export as a prompt to rotate access and contact support.",
        },
      ]
    }
    return [
      ...shared,
      {
        title: "4. Managing patient records",
        body: "Use Patient Records to search and open patient histories. All clinicians share the same clinic-wide record set, so coordinate care through the shared view.",
      },
    ]
  }, [isAdmin])

  function scrollToGuide() {
    guideRef.current?.scrollIntoView({ behavior: "smooth", block: "start" })
  }

  function downloadGuide() {
    const lines = [
      "# AURA-Dx Clinical Workflow Guide",
      isAdmin ? "(Administrator edition)" : "(Clinician edition)",
      "",
      "Support: " + SUPPORT_EMAIL,
      "",
      ...guideSections.flatMap((s) => ["## " + s.title, "", s.body, ""]),
      "---",
      "AURA-Dx is a thesis-stage research prototype and is not a certified diagnostic medical device.",
    ]
    const blob = new Blob([lines.join("\n")], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = isAdmin ? "AURA-Dx-Admin-Guide.md" : "AURA-Dx-Clinician-Guide.md"
    document.body.appendChild(a)
    a.click()
    a.remove()
    URL.revokeObjectURL(url)
  }

  return (
    <motion.div
      variants={container}
      initial="hidden"
      animate="show"
      className="mx-auto w-full max-w-5xl space-y-8"
    >
      {/* Header */}
      <motion.header
        variants={item}
        className="rounded-2xl border border-aura-border-soft bg-aura-bg-alt px-5 py-7 sm:px-8 sm:py-9"
      >
        <div className="flex items-start gap-3">
          <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-aura-accent/15 text-aura-accent">
            <LifeBuoy className="h-6 w-6" aria-hidden="true" />
          </span>
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-aura-text sm:text-[1.85rem]">
              Help &amp; Support Center
            </h1>
            <p className="mt-1 max-w-[60ch] text-sm leading-relaxed text-aura-muted">
              Find answers and documentation tailored to your{" "}
              <span className="font-medium text-aura-text">{isAdmin ? "administrator" : "clinician"}</span>{" "}
              role.
            </p>
          </div>
        </div>
      </motion.header>

      {/* Quick action: User Guide */}
      <motion.div variants={item}>
        <Card className="aura-lift rounded-2xl border-aura-border-soft bg-aura-bg-card shadow-aura-card">
          <CardHeader className="pb-3">
            <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-aura-accent-soft text-aura-accent-dark">
              <BookOpen className="h-5 w-5" aria-hidden="true" />
            </span>
            <CardTitle className="mt-3 text-lg text-aura-text">User Guide &amp; Documentation</CardTitle>
            <CardDescription className="text-aura-muted">
              View the clinical workflow guide inline, or download it for offline reference.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-2 sm:flex-row sm:items-center">
            <Button variant="outline" className="justify-center sm:w-auto" onClick={scrollToGuide}>
              <BookOpen className="mr-2 h-4 w-4" aria-hidden="true" />
              View guide
            </Button>
            <Button variant="outline" className="justify-center sm:w-auto" onClick={downloadGuide}>
              <Download className="mr-2 h-4 w-4" aria-hidden="true" />
              Download guide
            </Button>
          </CardContent>
        </Card>
      </motion.div>

      {/* FAQ accordions */}
      <section aria-label="Frequently asked questions" className="space-y-4">
        <motion.h2 variants={item} className="text-xl font-bold tracking-tight text-aura-text">
          Frequently Asked Questions
        </motion.h2>

        {loading ? (
          <HelpSkeleton />
        ) : (
          categories.map((cat) => {
            const Icon = cat.icon
            return (
              <motion.div key={cat.id} variants={item}>
                <Card className="overflow-hidden rounded-2xl border-aura-border-soft bg-aura-bg-card shadow-aura-card transition-shadow duration-300 hover:shadow-aura-card-hover">
                  <CardHeader className="flex-row items-center gap-3 space-y-0 border-b border-aura-border-soft pb-3">
                    <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-aura-accent-soft text-aura-accent-dark">
                      <Icon className="h-5 w-5" aria-hidden="true" />
                    </span>
                    <CardTitle className="text-base text-aura-text">{cat.label}</CardTitle>
                    <Badge variant="secondary" className="ml-auto bg-aura-surface-alt text-aura-muted">
                      {cat.items.length}
                    </Badge>
                  </CardHeader>
                  <CardContent className="divide-y divide-aura-border-soft p-0">
                    {cat.items.map((faq) => {
                      const id = `${cat.id}-${faq.q}`
                      const isOpen = openItems.has(id)
                      return (
                        <div key={id}>
                          <h3>
                            <button
                              type="button"
                              onClick={() => toggleItem(id)}
                              aria-expanded={isOpen}
                              aria-controls={`panel-${id}`}
                              id={`trigger-${id}`}
                              className="flex min-h-[44px] w-full items-center justify-between gap-4 px-5 py-4 text-left text-sm font-medium text-aura-text transition-colors hover:bg-aura-surface-alt focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-aura-accent"
                            >
                              {faq.q}
                              <ChevronDown
                                className={cn(
                                  "h-4 w-4 shrink-0 text-aura-muted transition-transform duration-300",
                                  isOpen && "rotate-180"
                                )}
                                aria-hidden="true"
                              />
                            </button>
                          </h3>
                          <AnimatePresence initial={false}>
                            {isOpen && (
                              <motion.div
                                key="panel"
                                id={`panel-${id}`}
                                role="region"
                                aria-labelledby={`trigger-${id}`}
                                initial={{ height: 0, opacity: 0 }}
                                animate={{ height: "auto", opacity: 1 }}
                                exit={{ height: 0, opacity: 0 }}
                                transition={{ duration: 0.28, ease: [0.4, 0, 0.2, 1] }}
                                className="overflow-hidden"
                              >
                                <p className="px-5 pb-5 text-sm leading-relaxed text-aura-muted">{faq.a}</p>
                              </motion.div>
                            )}
                          </AnimatePresence>
                        </div>
                      )
                    })}
                  </CardContent>
                </Card>
              </motion.div>
            )
          })
        )}
      </section>

      {/* In-page user guide */}
      <motion.section
        ref={guideRef}
        variants={item}
        aria-label="User guide"
        className="scroll-mt-24 space-y-4 rounded-2xl border border-aura-border-soft bg-aura-bg-card p-6 shadow-aura-card sm:p-8"
      >
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="text-xl font-bold tracking-tight text-aura-text">
              {isAdmin ? "Administrator" : "Clinician"} Workflow Guide
            </h2>
            <p className="mt-1 text-sm text-aura-muted">
              A quick reference for day-to-day use of AURA-Dx.
            </p>
          </div>
          <Button variant="outline" onClick={downloadGuide} className="shrink-0">
            <Download className="mr-2 h-4 w-4" aria-hidden="true" />
            Download
          </Button>
        </div>
        {loading ? (
          <div className="space-y-3" aria-hidden="true">
            <div className="h-4 w-2/3 animate-pulse rounded bg-aura-surface-alt" />
            <div className="h-3 w-full animate-pulse rounded bg-aura-surface-alt" />
            <div className="h-3 w-5/6 animate-pulse rounded bg-aura-surface-alt" />
          </div>
        ) : (
          <div className="space-y-5">
            {guideSections.map((s) => (
              <div key={s.title}>
                <h3 className="text-sm font-semibold text-aura-text">{s.title}</h3>
                <p className="mt-1 text-sm leading-relaxed text-aura-muted">{s.body}</p>
              </div>
            ))}
          </div>
        )}
      </motion.section>

      <Separator className="bg-aura-border-soft" />

      {/* Footer navigation back to legal */}
      <motion.footer
        variants={item}
        className="flex flex-col items-start justify-between gap-3 pb-2 sm:flex-row sm:items-center"
      >
        <p className="text-sm text-aura-muted">Need our privacy and data policies?</p>
        <Link
          to="/legal"
          className="inline-flex min-h-[44px] items-center gap-2 rounded-xl border border-aura-border-soft bg-aura-bg-card px-4 text-sm font-medium text-aura-text shadow-aura-xs transition-colors hover:bg-aura-surface-alt focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-aura-accent"
        >
          <ShieldCheck className="h-4 w-4 text-aura-accent" aria-hidden="true" />
          Legal &amp; Privacy
          <ArrowRight className="h-4 w-4 text-aura-muted" aria-hidden="true" />
        </Link>
      </motion.footer>
    </motion.div>
  )
}

function HelpSkeleton() {
  return (
    <div className="space-y-4" aria-hidden="true">
      {[0, 1, 2].map((i) => (
        <Card key={i} className="overflow-hidden rounded-2xl border-aura-border-soft bg-aura-bg-card shadow-aura-card">
          <CardContent className="space-y-3 p-5">
            <div className="flex items-center gap-3">
              <div className="h-9 w-9 animate-pulse rounded-lg bg-aura-surface-alt" />
              <div className="h-4 w-40 animate-pulse rounded bg-aura-surface-alt" />
            </div>
            <div className="h-3 w-full animate-pulse rounded bg-aura-surface-alt" />
            <div className="h-3 w-11/12 animate-pulse rounded bg-aura-surface-alt" />
            <div className="h-3 w-3/4 animate-pulse rounded bg-aura-surface-alt" />
          </CardContent>
        </Card>
      ))}
    </div>
  )
}
